/**
 * AUTO-GENERATED by `bun alea trading:gen-probability-table`.
 *
 * Do not edit by hand. Re-run the command to refresh; the live trader
 * loads this exact value at boot, so a stale table here means a stale
 * model in production.
 */

import type { ProbabilityTable } from "@alea/lib/trading/types";

export const probabilityTable: ProbabilityTable = {
  "command": "trading:gen-probability-table",
  "schemaVersion": 1,
  "generatedAtMs": 1777920827761,
  "series": {
    "source": "binance",
    "product": "perp",
    "timeframe": "5m"
  },
  "minBucketSamples": 200,
  "trainingRangeMs": {
    "firstWindowMs": 1683231540000,
    "lastWindowMs": 1777766340000
  },
  "assets": [
    {
      "asset": "btc",
      "windowCount": 315116,
      "alignedWindowShare": 0.5155656964419452,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 3,
              "samples": 3527,
              "probability": 0.963141480011341
            },
            {
              "distanceBp": 4,
              "samples": 5051,
              "probability": 0.9675311819441694
            },
            {
              "distanceBp": 5,
              "samples": 6525,
              "probability": 0.9744061302681992
            },
            {
              "distanceBp": 6,
              "samples": 7121,
              "probability": 0.9765482376070777
            },
            {
              "distanceBp": 7,
              "samples": 7562,
              "probability": 0.9777836551176937
            },
            {
              "distanceBp": 8,
              "samples": 7573,
              "probability": 0.9836260398785158
            }
          ],
          "2": [
            {
              "distanceBp": 3,
              "samples": 3433,
              "probability": 0.9172735217011361
            },
            {
              "distanceBp": 4,
              "samples": 4882,
              "probability": 0.9289225727160999
            },
            {
              "distanceBp": 5,
              "samples": 5985,
              "probability": 0.9308270676691729
            },
            {
              "distanceBp": 6,
              "samples": 6736,
              "probability": 0.9308194774346793
            },
            {
              "distanceBp": 7,
              "samples": 6940,
              "probability": 0.936743515850144
            },
            {
              "distanceBp": 8,
              "samples": 6814,
              "probability": 0.9377751687701791
            }
          ],
          "3": [
            {
              "distanceBp": 3,
              "samples": 2949,
              "probability": 0.8728382502543235
            },
            {
              "distanceBp": 4,
              "samples": 4068,
              "probability": 0.8793018682399213
            },
            {
              "distanceBp": 5,
              "samples": 5176,
              "probability": 0.8778979907264297
            },
            {
              "distanceBp": 6,
              "samples": 5580,
              "probability": 0.8801075268817204
            },
            {
              "distanceBp": 7,
              "samples": 5594,
              "probability": 0.8855917053986414
            },
            {
              "distanceBp": 8,
              "samples": 5305,
              "probability": 0.8897266729500471
            }
          ],
          "4": [
            {
              "distanceBp": 3,
              "samples": 1839,
              "probability": 0.8227297444263186
            },
            {
              "distanceBp": 4,
              "samples": 2493,
              "probability": 0.8198957079823506
            },
            {
              "distanceBp": 5,
              "samples": 3065,
              "probability": 0.8163132137030995
            },
            {
              "distanceBp": 6,
              "samples": 3146,
              "probability": 0.8254926891290527
            },
            {
              "distanceBp": 7,
              "samples": 2978,
              "probability": 0.8237071860308932
            },
            {
              "distanceBp": 8,
              "samples": 2855,
              "probability": 0.8245183887915937
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 3,
              "samples": 22810,
              "probability": 0.8378781236299868
            },
            {
              "distanceBp": 4,
              "samples": 18526,
              "probability": 0.8656482780956494
            },
            {
              "distanceBp": 5,
              "samples": 14578,
              "probability": 0.8842776786939224
            },
            {
              "distanceBp": 6,
              "samples": 11299,
              "probability": 0.9045933268430835
            },
            {
              "distanceBp": 7,
              "samples": 8419,
              "probability": 0.9091341014372253
            },
            {
              "distanceBp": 8,
              "samples": 6138,
              "probability": 0.9221244705115673
            }
          ],
          "2": [
            {
              "distanceBp": 3,
              "samples": 24883,
              "probability": 0.7597958445525057
            },
            {
              "distanceBp": 4,
              "samples": 20171,
              "probability": 0.781815477665956
            },
            {
              "distanceBp": 5,
              "samples": 15372,
              "probability": 0.8012620348685923
            },
            {
              "distanceBp": 6,
              "samples": 11819,
              "probability": 0.8211354598527795
            },
            {
              "distanceBp": 7,
              "samples": 8854,
              "probability": 0.8353286650101649
            },
            {
              "distanceBp": 8,
              "samples": 6664,
              "probability": 0.8400360144057623
            }
          ],
          "3": [
            {
              "distanceBp": 3,
              "samples": 27819,
              "probability": 0.7044466012437542
            },
            {
              "distanceBp": 4,
              "samples": 21755,
              "probability": 0.725764192139738
            },
            {
              "distanceBp": 5,
              "samples": 16721,
              "probability": 0.7485198253692961
            },
            {
              "distanceBp": 6,
              "samples": 12588,
              "probability": 0.7534953924372418
            },
            {
              "distanceBp": 7,
              "samples": 9396,
              "probability": 0.7636228182205194
            },
            {
              "distanceBp": 8,
              "samples": 7124,
              "probability": 0.7718978102189781
            }
          ],
          "4": [
            {
              "distanceBp": 3,
              "samples": 31477,
              "probability": 0.6579089493916193
            },
            {
              "distanceBp": 4,
              "samples": 23663,
              "probability": 0.6821197650340194
            },
            {
              "distanceBp": 5,
              "samples": 17475,
              "probability": 0.6931616595135909
            },
            {
              "distanceBp": 6,
              "samples": 12614,
              "probability": 0.701759949262724
            },
            {
              "distanceBp": 7,
              "samples": 9118,
              "probability": 0.7102434744461504
            },
            {
              "distanceBp": 8,
              "samples": 6552,
              "probability": 0.7220695970695971
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 3,
        "endBp": 8,
        "calibrationScore": 0.009382444305534221,
        "coverageFraction": 0.3817586222216581
      }
    },
    {
      "asset": "eth",
      "windowCount": 315116,
      "alignedWindowShare": 0.4865224234884931,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 5,
              "samples": 2696,
              "probability": 0.9799703264094956
            },
            {
              "distanceBp": 6,
              "samples": 3377,
              "probability": 0.9769025762511104
            },
            {
              "distanceBp": 7,
              "samples": 4180,
              "probability": 0.9820574162679426
            },
            {
              "distanceBp": 8,
              "samples": 4661,
              "probability": 0.984123578631195
            },
            {
              "distanceBp": 9,
              "samples": 5033,
              "probability": 0.9803298231670972
            },
            {
              "distanceBp": 10,
              "samples": 5323,
              "probability": 0.9844072891226752
            },
            {
              "distanceBp": 11,
              "samples": 5366,
              "probability": 0.9837868058143869
            }
          ],
          "2": [
            {
              "distanceBp": 5,
              "samples": 2580,
              "probability": 0.9232558139534883
            },
            {
              "distanceBp": 6,
              "samples": 3249,
              "probability": 0.9347491535857186
            },
            {
              "distanceBp": 7,
              "samples": 3914,
              "probability": 0.9345937659683189
            },
            {
              "distanceBp": 8,
              "samples": 4303,
              "probability": 0.9356263072275157
            },
            {
              "distanceBp": 9,
              "samples": 4422,
              "probability": 0.942107643600181
            },
            {
              "distanceBp": 10,
              "samples": 4772,
              "probability": 0.9404861693210393
            },
            {
              "distanceBp": 11,
              "samples": 4781,
              "probability": 0.9483371679564945
            }
          ],
          "3": [
            {
              "distanceBp": 5,
              "samples": 2204,
              "probability": 0.8888384754990926
            },
            {
              "distanceBp": 6,
              "samples": 2625,
              "probability": 0.8819047619047619
            },
            {
              "distanceBp": 7,
              "samples": 3056,
              "probability": 0.8887434554973822
            },
            {
              "distanceBp": 8,
              "samples": 3526,
              "probability": 0.8865570051049347
            },
            {
              "distanceBp": 9,
              "samples": 3764,
              "probability": 0.890807651434644
            },
            {
              "distanceBp": 10,
              "samples": 3805,
              "probability": 0.8956636005256242
            },
            {
              "distanceBp": 11,
              "samples": 3653,
              "probability": 0.9039145907473309
            }
          ],
          "4": [
            {
              "distanceBp": 5,
              "samples": 1278,
              "probability": 0.8192488262910798
            },
            {
              "distanceBp": 6,
              "samples": 1538,
              "probability": 0.811443433029909
            },
            {
              "distanceBp": 7,
              "samples": 1786,
              "probability": 0.8157894736842105
            },
            {
              "distanceBp": 8,
              "samples": 1840,
              "probability": 0.8201086956521739
            },
            {
              "distanceBp": 9,
              "samples": 2030,
              "probability": 0.8418719211822661
            },
            {
              "distanceBp": 10,
              "samples": 2023,
              "probability": 0.8294611962432031
            },
            {
              "distanceBp": 11,
              "samples": 1885,
              "probability": 0.8366047745358091
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 5,
              "samples": 16100,
              "probability": 0.8554037267080745
            },
            {
              "distanceBp": 6,
              "samples": 13542,
              "probability": 0.8817752178407916
            },
            {
              "distanceBp": 7,
              "samples": 11350,
              "probability": 0.8897797356828194
            },
            {
              "distanceBp": 8,
              "samples": 9566,
              "probability": 0.9062303993309638
            },
            {
              "distanceBp": 9,
              "samples": 7529,
              "probability": 0.9126045955638199
            },
            {
              "distanceBp": 10,
              "samples": 6189,
              "probability": 0.924866698982065
            },
            {
              "distanceBp": 11,
              "samples": 4973,
              "probability": 0.9350492660365977
            }
          ],
          "2": [
            {
              "distanceBp": 5,
              "samples": 17361,
              "probability": 0.7784113818328438
            },
            {
              "distanceBp": 6,
              "samples": 14837,
              "probability": 0.7983419828806363
            },
            {
              "distanceBp": 7,
              "samples": 12155,
              "probability": 0.8097079391197038
            },
            {
              "distanceBp": 8,
              "samples": 10009,
              "probability": 0.8331501648516335
            },
            {
              "distanceBp": 9,
              "samples": 7907,
              "probability": 0.8328063740988997
            },
            {
              "distanceBp": 10,
              "samples": 6399,
              "probability": 0.8412251914361619
            },
            {
              "distanceBp": 11,
              "samples": 5186,
              "probability": 0.8540300809872734
            }
          ],
          "3": [
            {
              "distanceBp": 5,
              "samples": 18941,
              "probability": 0.7211340478327438
            },
            {
              "distanceBp": 6,
              "samples": 15922,
              "probability": 0.7428086923753298
            },
            {
              "distanceBp": 7,
              "samples": 13007,
              "probability": 0.7466748673791036
            },
            {
              "distanceBp": 8,
              "samples": 10331,
              "probability": 0.7629464717839513
            },
            {
              "distanceBp": 9,
              "samples": 8350,
              "probability": 0.7661077844311377
            },
            {
              "distanceBp": 10,
              "samples": 6644,
              "probability": 0.786724864539434
            },
            {
              "distanceBp": 11,
              "samples": 5425,
              "probability": 0.7821198156682028
            }
          ],
          "4": [
            {
              "distanceBp": 5,
              "samples": 20582,
              "probability": 0.6695170537362745
            },
            {
              "distanceBp": 6,
              "samples": 16654,
              "probability": 0.6934670349465594
            },
            {
              "distanceBp": 7,
              "samples": 13065,
              "probability": 0.6982778415614237
            },
            {
              "distanceBp": 8,
              "samples": 10222,
              "probability": 0.7110154568577578
            },
            {
              "distanceBp": 9,
              "samples": 7926,
              "probability": 0.719404491546808
            },
            {
              "distanceBp": 10,
              "samples": 6207,
              "probability": 0.7272434348316417
            },
            {
              "distanceBp": 11,
              "samples": 4762,
              "probability": 0.7181856362872743
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 5,
        "endBp": 11,
        "calibrationScore": 0.008933547736620244,
        "coverageFraction": 0.30662041914723465
      }
    },
    {
      "asset": "sol",
      "windowCount": 315116,
      "alignedWindowShare": 0.4927296614580028,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 11,
              "samples": 2676,
              "probability": 0.9775784753363229
            },
            {
              "distanceBp": 12,
              "samples": 3024,
              "probability": 0.9837962962962963
            },
            {
              "distanceBp": 13,
              "samples": 3346,
              "probability": 0.9814704124327556
            },
            {
              "distanceBp": 14,
              "samples": 3675,
              "probability": 0.9814965986394558
            },
            {
              "distanceBp": 15,
              "samples": 3906,
              "probability": 0.9866871479774706
            },
            {
              "distanceBp": 16,
              "samples": 3960,
              "probability": 0.9861111111111112
            },
            {
              "distanceBp": 17,
              "samples": 3980,
              "probability": 0.9851758793969849
            },
            {
              "distanceBp": 18,
              "samples": 3842,
              "probability": 0.9885476314419573
            }
          ],
          "2": [
            {
              "distanceBp": 11,
              "samples": 2563,
              "probability": 0.9266484588373001
            },
            {
              "distanceBp": 12,
              "samples": 2951,
              "probability": 0.9383259911894273
            },
            {
              "distanceBp": 13,
              "samples": 3140,
              "probability": 0.9328025477707006
            },
            {
              "distanceBp": 14,
              "samples": 3475,
              "probability": 0.9398561151079137
            },
            {
              "distanceBp": 15,
              "samples": 3597,
              "probability": 0.9407839866555463
            },
            {
              "distanceBp": 16,
              "samples": 3404,
              "probability": 0.935957696827262
            },
            {
              "distanceBp": 17,
              "samples": 3665,
              "probability": 0.9489768076398363
            },
            {
              "distanceBp": 18,
              "samples": 3505,
              "probability": 0.9463623395149786
            }
          ],
          "3": [
            {
              "distanceBp": 11,
              "samples": 2167,
              "probability": 0.8763267189663129
            },
            {
              "distanceBp": 12,
              "samples": 2443,
              "probability": 0.8956201391731478
            },
            {
              "distanceBp": 13,
              "samples": 2627,
              "probability": 0.8759040730871717
            },
            {
              "distanceBp": 14,
              "samples": 2847,
              "probability": 0.8770635756937126
            },
            {
              "distanceBp": 15,
              "samples": 2865,
              "probability": 0.8900523560209425
            },
            {
              "distanceBp": 16,
              "samples": 2953,
              "probability": 0.8821537419573315
            },
            {
              "distanceBp": 17,
              "samples": 2870,
              "probability": 0.8968641114982578
            },
            {
              "distanceBp": 18,
              "samples": 2794,
              "probability": 0.9058697208303508
            }
          ],
          "4": [
            {
              "distanceBp": 11,
              "samples": 1248,
              "probability": 0.8229166666666666
            },
            {
              "distanceBp": 12,
              "samples": 1337,
              "probability": 0.8309648466716529
            },
            {
              "distanceBp": 13,
              "samples": 1472,
              "probability": 0.826766304347826
            },
            {
              "distanceBp": 14,
              "samples": 1567,
              "probability": 0.822590938098277
            },
            {
              "distanceBp": 15,
              "samples": 1461,
              "probability": 0.8357289527720739
            },
            {
              "distanceBp": 16,
              "samples": 1529,
              "probability": 0.8384565075212557
            },
            {
              "distanceBp": 17,
              "samples": 1364,
              "probability": 0.8291788856304986
            },
            {
              "distanceBp": 18,
              "samples": 1322,
              "probability": 0.8388804841149773
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 11,
              "samples": 7745,
              "probability": 0.9017430600387347
            },
            {
              "distanceBp": 12,
              "samples": 6730,
              "probability": 0.9034175334323923
            },
            {
              "distanceBp": 13,
              "samples": 5830,
              "probability": 0.9087478559176673
            },
            {
              "distanceBp": 14,
              "samples": 5105,
              "probability": 0.9198824681684623
            },
            {
              "distanceBp": 15,
              "samples": 4240,
              "probability": 0.9261792452830189
            },
            {
              "distanceBp": 16,
              "samples": 3634,
              "probability": 0.9350577875619153
            },
            {
              "distanceBp": 17,
              "samples": 3178,
              "probability": 0.9254247954688484
            },
            {
              "distanceBp": 18,
              "samples": 2578,
              "probability": 0.9344453064391001
            }
          ],
          "2": [
            {
              "distanceBp": 11,
              "samples": 8205,
              "probability": 0.8260816575258988
            },
            {
              "distanceBp": 12,
              "samples": 6972,
              "probability": 0.8369191049913941
            },
            {
              "distanceBp": 13,
              "samples": 6202,
              "probability": 0.8350532086423734
            },
            {
              "distanceBp": 14,
              "samples": 5232,
              "probability": 0.8363914373088684
            },
            {
              "distanceBp": 15,
              "samples": 4582,
              "probability": 0.8408991706678306
            },
            {
              "distanceBp": 16,
              "samples": 3829,
              "probability": 0.8469574301384173
            },
            {
              "distanceBp": 17,
              "samples": 3192,
              "probability": 0.8455513784461153
            },
            {
              "distanceBp": 18,
              "samples": 2684,
              "probability": 0.8580476900149031
            }
          ],
          "3": [
            {
              "distanceBp": 11,
              "samples": 8877,
              "probability": 0.7606173256730877
            },
            {
              "distanceBp": 12,
              "samples": 7514,
              "probability": 0.7631088634548843
            },
            {
              "distanceBp": 13,
              "samples": 6434,
              "probability": 0.7805408765930991
            },
            {
              "distanceBp": 14,
              "samples": 5440,
              "probability": 0.7801470588235294
            },
            {
              "distanceBp": 15,
              "samples": 4635,
              "probability": 0.7797195253505933
            },
            {
              "distanceBp": 16,
              "samples": 3800,
              "probability": 0.7871052631578948
            },
            {
              "distanceBp": 17,
              "samples": 3360,
              "probability": 0.7848214285714286
            },
            {
              "distanceBp": 18,
              "samples": 2826,
              "probability": 0.7926397735314933
            }
          ],
          "4": [
            {
              "distanceBp": 11,
              "samples": 8772,
              "probability": 0.7065663474692202
            },
            {
              "distanceBp": 12,
              "samples": 7459,
              "probability": 0.7105510122000268
            },
            {
              "distanceBp": 13,
              "samples": 6164,
              "probability": 0.7255029201817002
            },
            {
              "distanceBp": 14,
              "samples": 5047,
              "probability": 0.7273627897761046
            },
            {
              "distanceBp": 15,
              "samples": 4361,
              "probability": 0.7174959871589085
            },
            {
              "distanceBp": 16,
              "samples": 3626,
              "probability": 0.728626585769443
            },
            {
              "distanceBp": 17,
              "samples": 3045,
              "probability": 0.7372742200328407
            },
            {
              "distanceBp": 18,
              "samples": 2602,
              "probability": 0.7444273635664873
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 11,
        "endBp": 18,
        "calibrationScore": 0.008949176380546152,
        "coverageFraction": 0.19054491044567715
      }
    },
    {
      "asset": "xrp",
      "windowCount": 315116,
      "alignedWindowShare": 0.48223511341855063,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 7,
              "samples": 3150,
              "probability": 0.9733333333333334
            },
            {
              "distanceBp": 8,
              "samples": 3272,
              "probability": 0.9721882640586798
            },
            {
              "distanceBp": 9,
              "samples": 4709,
              "probability": 0.9772775536207262
            },
            {
              "distanceBp": 10,
              "samples": 3898,
              "probability": 0.9748589020010262
            },
            {
              "distanceBp": 11,
              "samples": 5425,
              "probability": 0.9834101382488479
            },
            {
              "distanceBp": 12,
              "samples": 4435,
              "probability": 0.9828635851183766
            },
            {
              "distanceBp": 13,
              "samples": 4823,
              "probability": 0.9877669500311009
            },
            {
              "distanceBp": 14,
              "samples": 4515,
              "probability": 0.9844961240310077
            }
          ],
          "2": [
            {
              "distanceBp": 7,
              "samples": 3023,
              "probability": 0.928217002977175
            },
            {
              "distanceBp": 8,
              "samples": 3129,
              "probability": 0.9181847235538511
            },
            {
              "distanceBp": 9,
              "samples": 4273,
              "probability": 0.9347062953428504
            },
            {
              "distanceBp": 10,
              "samples": 3543,
              "probability": 0.9410104431272932
            },
            {
              "distanceBp": 11,
              "samples": 4898,
              "probability": 0.9458962841976317
            },
            {
              "distanceBp": 12,
              "samples": 4003,
              "probability": 0.9447914064451661
            },
            {
              "distanceBp": 13,
              "samples": 4143,
              "probability": 0.9437605599806903
            },
            {
              "distanceBp": 14,
              "samples": 3968,
              "probability": 0.953125
            }
          ],
          "3": [
            {
              "distanceBp": 7,
              "samples": 2528,
              "probability": 0.872626582278481
            },
            {
              "distanceBp": 8,
              "samples": 2572,
              "probability": 0.8720839813374806
            },
            {
              "distanceBp": 9,
              "samples": 3529,
              "probability": 0.8897704732218759
            },
            {
              "distanceBp": 10,
              "samples": 2876,
              "probability": 0.8890820584144645
            },
            {
              "distanceBp": 11,
              "samples": 3855,
              "probability": 0.8985732814526589
            },
            {
              "distanceBp": 12,
              "samples": 3172,
              "probability": 0.9035308953341741
            },
            {
              "distanceBp": 13,
              "samples": 3243,
              "probability": 0.8979340117175455
            },
            {
              "distanceBp": 14,
              "samples": 3137,
              "probability": 0.9034109021357986
            }
          ],
          "4": [
            {
              "distanceBp": 7,
              "samples": 1579,
              "probability": 0.8169727675744142
            },
            {
              "distanceBp": 8,
              "samples": 1463,
              "probability": 0.8393711551606289
            },
            {
              "distanceBp": 9,
              "samples": 1950,
              "probability": 0.8374358974358974
            },
            {
              "distanceBp": 10,
              "samples": 1608,
              "probability": 0.8376865671641791
            },
            {
              "distanceBp": 11,
              "samples": 2057,
              "probability": 0.822070977151191
            },
            {
              "distanceBp": 12,
              "samples": 1570,
              "probability": 0.8382165605095542
            },
            {
              "distanceBp": 13,
              "samples": 1576,
              "probability": 0.8464467005076142
            },
            {
              "distanceBp": 14,
              "samples": 1537,
              "probability": 0.8516590761223162
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 7,
              "samples": 11764,
              "probability": 0.8798027881672901
            },
            {
              "distanceBp": 8,
              "samples": 9576,
              "probability": 0.8893065998329156
            },
            {
              "distanceBp": 9,
              "samples": 8590,
              "probability": 0.9039580908032596
            },
            {
              "distanceBp": 10,
              "samples": 6395,
              "probability": 0.9053948397185301
            },
            {
              "distanceBp": 11,
              "samples": 5893,
              "probability": 0.9107415577804174
            },
            {
              "distanceBp": 12,
              "samples": 4541,
              "probability": 0.910372164721427
            },
            {
              "distanceBp": 13,
              "samples": 3929,
              "probability": 0.9180453041486384
            },
            {
              "distanceBp": 14,
              "samples": 3196,
              "probability": 0.9205256570713392
            }
          ],
          "2": [
            {
              "distanceBp": 7,
              "samples": 12375,
              "probability": 0.7983030303030303
            },
            {
              "distanceBp": 8,
              "samples": 10371,
              "probability": 0.812747083212805
            },
            {
              "distanceBp": 9,
              "samples": 9071,
              "probability": 0.8134715025906736
            },
            {
              "distanceBp": 10,
              "samples": 6567,
              "probability": 0.8213796253997259
            },
            {
              "distanceBp": 11,
              "samples": 6185,
              "probability": 0.8337914308811641
            },
            {
              "distanceBp": 12,
              "samples": 4788,
              "probability": 0.8279030910609858
            },
            {
              "distanceBp": 13,
              "samples": 4116,
              "probability": 0.8483965014577259
            },
            {
              "distanceBp": 14,
              "samples": 3398,
              "probability": 0.8446144791053561
            }
          ],
          "3": [
            {
              "distanceBp": 7,
              "samples": 13034,
              "probability": 0.7425962866349547
            },
            {
              "distanceBp": 8,
              "samples": 11211,
              "probability": 0.7536348229417537
            },
            {
              "distanceBp": 9,
              "samples": 9645,
              "probability": 0.7578019699326076
            },
            {
              "distanceBp": 10,
              "samples": 7027,
              "probability": 0.7576490678810303
            },
            {
              "distanceBp": 11,
              "samples": 6477,
              "probability": 0.7639339200247028
            },
            {
              "distanceBp": 12,
              "samples": 4868,
              "probability": 0.7738290879211175
            },
            {
              "distanceBp": 13,
              "samples": 4306,
              "probability": 0.784486762656758
            },
            {
              "distanceBp": 14,
              "samples": 3514,
              "probability": 0.7754695503699488
            }
          ],
          "4": [
            {
              "distanceBp": 7,
              "samples": 13607,
              "probability": 0.6875137796722275
            },
            {
              "distanceBp": 8,
              "samples": 10956,
              "probability": 0.6966958744067178
            },
            {
              "distanceBp": 9,
              "samples": 9320,
              "probability": 0.7002145922746781
            },
            {
              "distanceBp": 10,
              "samples": 6788,
              "probability": 0.7018267530936948
            },
            {
              "distanceBp": 11,
              "samples": 6262,
              "probability": 0.7123922069626317
            },
            {
              "distanceBp": 12,
              "samples": 4514,
              "probability": 0.7162162162162162
            },
            {
              "distanceBp": 13,
              "samples": 3961,
              "probability": 0.7167381974248928
            },
            {
              "distanceBp": 14,
              "samples": 3195,
              "probability": 0.741471048513302
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 7,
        "endBp": 14,
        "calibrationScore": 0.010290302705209486,
        "coverageFraction": 0.255156831135201
      }
    },
    {
      "asset": "doge",
      "windowCount": 315116,
      "alignedWindowShare": 0.4887787354498026,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 8,
              "samples": 2449,
              "probability": 0.9828501429154757
            },
            {
              "distanceBp": 9,
              "samples": 2852,
              "probability": 0.9747545582047685
            },
            {
              "distanceBp": 10,
              "samples": 2565,
              "probability": 0.9777777777777777
            },
            {
              "distanceBp": 11,
              "samples": 3459,
              "probability": 0.9812084417461694
            },
            {
              "distanceBp": 12,
              "samples": 3569,
              "probability": 0.9806668534603531
            },
            {
              "distanceBp": 13,
              "samples": 3479,
              "probability": 0.9847657372808278
            },
            {
              "distanceBp": 14,
              "samples": 3777,
              "probability": 0.9851734180566587
            },
            {
              "distanceBp": 15,
              "samples": 3600,
              "probability": 0.9825
            },
            {
              "distanceBp": 16,
              "samples": 3798,
              "probability": 0.9876250658241179
            }
          ],
          "2": [
            {
              "distanceBp": 8,
              "samples": 2269,
              "probability": 0.9338915821947995
            },
            {
              "distanceBp": 9,
              "samples": 2620,
              "probability": 0.9286259541984733
            },
            {
              "distanceBp": 10,
              "samples": 2385,
              "probability": 0.9228511530398323
            },
            {
              "distanceBp": 11,
              "samples": 3221,
              "probability": 0.944737659112077
            },
            {
              "distanceBp": 12,
              "samples": 3268,
              "probability": 0.9498164014687882
            },
            {
              "distanceBp": 13,
              "samples": 3164,
              "probability": 0.9396333754740834
            },
            {
              "distanceBp": 14,
              "samples": 3345,
              "probability": 0.9482810164424514
            },
            {
              "distanceBp": 15,
              "samples": 3241,
              "probability": 0.949089787102746
            },
            {
              "distanceBp": 16,
              "samples": 3427,
              "probability": 0.9471841260577765
            }
          ],
          "3": [
            {
              "distanceBp": 8,
              "samples": 1867,
              "probability": 0.888055704338511
            },
            {
              "distanceBp": 9,
              "samples": 2177,
              "probability": 0.8879191548001837
            },
            {
              "distanceBp": 10,
              "samples": 2010,
              "probability": 0.8791044776119403
            },
            {
              "distanceBp": 11,
              "samples": 2602,
              "probability": 0.8966179861644888
            },
            {
              "distanceBp": 12,
              "samples": 2627,
              "probability": 0.8976018271792919
            },
            {
              "distanceBp": 13,
              "samples": 2672,
              "probability": 0.9038173652694611
            },
            {
              "distanceBp": 14,
              "samples": 2752,
              "probability": 0.8822674418604651
            },
            {
              "distanceBp": 15,
              "samples": 2594,
              "probability": 0.89745566692367
            },
            {
              "distanceBp": 16,
              "samples": 2646,
              "probability": 0.9021164021164021
            }
          ],
          "4": [
            {
              "distanceBp": 8,
              "samples": 1059,
              "probability": 0.8498583569405099
            },
            {
              "distanceBp": 9,
              "samples": 1148,
              "probability": 0.8257839721254355
            },
            {
              "distanceBp": 10,
              "samples": 1188,
              "probability": 0.8240740740740741
            },
            {
              "distanceBp": 11,
              "samples": 1386,
              "probability": 0.8441558441558441
            },
            {
              "distanceBp": 12,
              "samples": 1371,
              "probability": 0.8081692195477753
            },
            {
              "distanceBp": 13,
              "samples": 1329,
              "probability": 0.8299473288186606
            },
            {
              "distanceBp": 14,
              "samples": 1372,
              "probability": 0.8469387755102041
            },
            {
              "distanceBp": 15,
              "samples": 1298,
              "probability": 0.8289676425269645
            },
            {
              "distanceBp": 16,
              "samples": 1347,
              "probability": 0.8307349665924276
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 8,
              "samples": 10406,
              "probability": 0.8740149913511436
            },
            {
              "distanceBp": 9,
              "samples": 9064,
              "probability": 0.8857016769638129
            },
            {
              "distanceBp": 10,
              "samples": 7707,
              "probability": 0.8921759439470611
            },
            {
              "distanceBp": 11,
              "samples": 7041,
              "probability": 0.9042749609430478
            },
            {
              "distanceBp": 12,
              "samples": 5957,
              "probability": 0.9127077387946954
            },
            {
              "distanceBp": 13,
              "samples": 5068,
              "probability": 0.9141673243883188
            },
            {
              "distanceBp": 14,
              "samples": 4444,
              "probability": 0.9183168316831684
            },
            {
              "distanceBp": 15,
              "samples": 3792,
              "probability": 0.9232594936708861
            },
            {
              "distanceBp": 16,
              "samples": 3396,
              "probability": 0.9296230859835101
            }
          ],
          "2": [
            {
              "distanceBp": 8,
              "samples": 11361,
              "probability": 0.8014259308159493
            },
            {
              "distanceBp": 9,
              "samples": 9675,
              "probability": 0.8024806201550387
            },
            {
              "distanceBp": 10,
              "samples": 8249,
              "probability": 0.8139168384046551
            },
            {
              "distanceBp": 11,
              "samples": 7316,
              "probability": 0.8180699835975943
            },
            {
              "distanceBp": 12,
              "samples": 6191,
              "probability": 0.8329833629462122
            },
            {
              "distanceBp": 13,
              "samples": 5321,
              "probability": 0.8267242999436196
            },
            {
              "distanceBp": 14,
              "samples": 4539,
              "probability": 0.8435778805904385
            },
            {
              "distanceBp": 15,
              "samples": 4019,
              "probability": 0.8424981338641453
            },
            {
              "distanceBp": 16,
              "samples": 3443,
              "probability": 0.8449027011327331
            }
          ],
          "3": [
            {
              "distanceBp": 8,
              "samples": 11952,
              "probability": 0.7407128514056225
            },
            {
              "distanceBp": 9,
              "samples": 10354,
              "probability": 0.7514004249565386
            },
            {
              "distanceBp": 10,
              "samples": 8642,
              "probability": 0.7512149965285814
            },
            {
              "distanceBp": 11,
              "samples": 7751,
              "probability": 0.76519158818217
            },
            {
              "distanceBp": 12,
              "samples": 6714,
              "probability": 0.7755436401549002
            },
            {
              "distanceBp": 13,
              "samples": 5604,
              "probability": 0.7665952890792291
            },
            {
              "distanceBp": 14,
              "samples": 4781,
              "probability": 0.7726417067559088
            },
            {
              "distanceBp": 15,
              "samples": 4190,
              "probability": 0.7720763723150358
            },
            {
              "distanceBp": 16,
              "samples": 3524,
              "probability": 0.79738933030647
            }
          ],
          "4": [
            {
              "distanceBp": 8,
              "samples": 12843,
              "probability": 0.6919722806197929
            },
            {
              "distanceBp": 9,
              "samples": 10848,
              "probability": 0.7002212389380531
            },
            {
              "distanceBp": 10,
              "samples": 9018,
              "probability": 0.7072521623419827
            },
            {
              "distanceBp": 11,
              "samples": 7741,
              "probability": 0.7120527063686862
            },
            {
              "distanceBp": 12,
              "samples": 6497,
              "probability": 0.7121748499307372
            },
            {
              "distanceBp": 13,
              "samples": 5452,
              "probability": 0.7239545121056493
            },
            {
              "distanceBp": 14,
              "samples": 4647,
              "probability": 0.7153001936733376
            },
            {
              "distanceBp": 15,
              "samples": 3822,
              "probability": 0.7250130821559393
            },
            {
              "distanceBp": 16,
              "samples": 3322,
              "probability": 0.7260686333534015
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 8,
        "endBp": 16,
        "calibrationScore": 0.00933793057751321,
        "coverageFraction": 0.25487360210208304
      }
    }
  ]
};
