/**
 * AUTO-GENERATED by `bun alea trading:gen-probability-table`.
 *
 * Do not edit by hand. Re-run the command to refresh; the live trader
 * loads this exact value at boot, so a stale table here means a stale
 * model in production.
 */

import type { ProbabilityTable } from "@alea/lib/trading/types";

export const probabilityTable: ProbabilityTable = {
  "command": "trading:gen-probability-table",
  "schemaVersion": 1,
  "generatedAtMs": 1777935452144,
  "series": {
    "source": "binance",
    "product": "perp",
    "timeframe": "5m"
  },
  "minBucketSamples": 200,
  "trainingRangeMs": {
    "firstWindowMs": 1683231540000,
    "lastWindowMs": 1777766340000
  },
  "assets": [
    {
      "asset": "btc",
      "windowCount": 315116,
      "alignedWindowShare": 0.5414418817197476,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 2,
              "samples": 2731,
              "probability": 0.9498352251922373
            },
            {
              "distanceBp": 3,
              "samples": 4777,
              "probability": 0.9579233828762822
            },
            {
              "distanceBp": 4,
              "samples": 6357,
              "probability": 0.9642913323894919
            },
            {
              "distanceBp": 5,
              "samples": 7744,
              "probability": 0.9697830578512396
            },
            {
              "distanceBp": 6,
              "samples": 8109,
              "probability": 0.9750894068319151
            },
            {
              "distanceBp": 7,
              "samples": 8215,
              "probability": 0.9763846622032867
            },
            {
              "distanceBp": 8,
              "samples": 8026,
              "probability": 0.9816845252927984
            },
            {
              "distanceBp": 9,
              "samples": 7610,
              "probability": 0.9843626806833115
            }
          ],
          "2": [
            {
              "distanceBp": 2,
              "samples": 2806,
              "probability": 0.8920171062009978
            },
            {
              "distanceBp": 3,
              "samples": 4603,
              "probability": 0.9087551596784705
            },
            {
              "distanceBp": 4,
              "samples": 6194,
              "probability": 0.9168550209880529
            },
            {
              "distanceBp": 5,
              "samples": 7212,
              "probability": 0.9227676095396561
            },
            {
              "distanceBp": 6,
              "samples": 7741,
              "probability": 0.9259785557421522
            },
            {
              "distanceBp": 7,
              "samples": 7550,
              "probability": 0.9374834437086093
            },
            {
              "distanceBp": 8,
              "samples": 7261,
              "probability": 0.9376118991874397
            },
            {
              "distanceBp": 9,
              "samples": 6649,
              "probability": 0.9473605053391487
            }
          ],
          "3": [
            {
              "distanceBp": 2,
              "samples": 2662,
              "probability": 0.8425995492111195
            },
            {
              "distanceBp": 3,
              "samples": 4133,
              "probability": 0.8519235422211469
            },
            {
              "distanceBp": 4,
              "samples": 5266,
              "probability": 0.8668818837827573
            },
            {
              "distanceBp": 5,
              "samples": 6312,
              "probability": 0.8742078580481623
            },
            {
              "distanceBp": 6,
              "samples": 6441,
              "probability": 0.8764167054805154
            },
            {
              "distanceBp": 7,
              "samples": 6149,
              "probability": 0.8785168320052041
            },
            {
              "distanceBp": 8,
              "samples": 5662,
              "probability": 0.8874955845990816
            },
            {
              "distanceBp": 9,
              "samples": 5381,
              "probability": 0.8957442854488014
            }
          ],
          "4": [
            {
              "distanceBp": 2,
              "samples": 1846,
              "probability": 0.7936078006500542
            },
            {
              "distanceBp": 3,
              "samples": 2776,
              "probability": 0.8108789625360231
            },
            {
              "distanceBp": 4,
              "samples": 3444,
              "probability": 0.8019744483159117
            },
            {
              "distanceBp": 5,
              "samples": 3854,
              "probability": 0.8134405812143228
            },
            {
              "distanceBp": 6,
              "samples": 3644,
              "probability": 0.8301317233809001
            },
            {
              "distanceBp": 7,
              "samples": 3271,
              "probability": 0.8294099663711403
            },
            {
              "distanceBp": 8,
              "samples": 3007,
              "probability": 0.8270701696042567
            },
            {
              "distanceBp": 9,
              "samples": 2577,
              "probability": 0.8393480791618161
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 2,
              "samples": 26424,
              "probability": 0.789320314865274
            },
            {
              "distanceBp": 3,
              "samples": 21560,
              "probability": 0.8317717996289424
            },
            {
              "distanceBp": 4,
              "samples": 17220,
              "probability": 0.8591173054587689
            },
            {
              "distanceBp": 5,
              "samples": 13359,
              "probability": 0.8787334381315967
            },
            {
              "distanceBp": 6,
              "samples": 10311,
              "probability": 0.8988458927359131
            },
            {
              "distanceBp": 7,
              "samples": 7766,
              "probability": 0.9048416173062065
            },
            {
              "distanceBp": 8,
              "samples": 5685,
              "probability": 0.9199648197009674
            },
            {
              "distanceBp": 9,
              "samples": 4506,
              "probability": 0.9214380825565912
            }
          ],
          "2": [
            {
              "distanceBp": 2,
              "samples": 29043,
              "probability": 0.7126329924594567
            },
            {
              "distanceBp": 3,
              "samples": 23713,
              "probability": 0.7536794163538987
            },
            {
              "distanceBp": 4,
              "samples": 18859,
              "probability": 0.7755448327058698
            },
            {
              "distanceBp": 5,
              "samples": 14145,
              "probability": 0.7941322021915871
            },
            {
              "distanceBp": 6,
              "samples": 10814,
              "probability": 0.8144072498612909
            },
            {
              "distanceBp": 7,
              "samples": 8244,
              "probability": 0.8271470160116449
            },
            {
              "distanceBp": 8,
              "samples": 6217,
              "probability": 0.8331992922631495
            },
            {
              "distanceBp": 9,
              "samples": 4689,
              "probability": 0.8419705694177864
            }
          ],
          "3": [
            {
              "distanceBp": 2,
              "samples": 32948,
              "probability": 0.6650176034964186
            },
            {
              "distanceBp": 3,
              "samples": 26635,
              "probability": 0.7002064952130655
            },
            {
              "distanceBp": 4,
              "samples": 20557,
              "probability": 0.7199980541907866
            },
            {
              "distanceBp": 5,
              "samples": 15585,
              "probability": 0.7405838947706128
            },
            {
              "distanceBp": 6,
              "samples": 11727,
              "probability": 0.7462266564338705
            },
            {
              "distanceBp": 7,
              "samples": 8841,
              "probability": 0.7608867775138559
            },
            {
              "distanceBp": 8,
              "samples": 6767,
              "probability": 0.7675483966307078
            },
            {
              "distanceBp": 9,
              "samples": 4874,
              "probability": 0.7673368896183833
            }
          ],
          "4": [
            {
              "distanceBp": 2,
              "samples": 40054,
              "probability": 0.6278024666699955
            },
            {
              "distanceBp": 3,
              "samples": 30540,
              "probability": 0.6539292730844793
            },
            {
              "distanceBp": 4,
              "samples": 22712,
              "probability": 0.6790683339203945
            },
            {
              "distanceBp": 5,
              "samples": 16686,
              "probability": 0.6880019177753806
            },
            {
              "distanceBp": 6,
              "samples": 12116,
              "probability": 0.6952789699570815
            },
            {
              "distanceBp": 7,
              "samples": 8825,
              "probability": 0.7043626062322946
            },
            {
              "distanceBp": 8,
              "samples": 6400,
              "probability": 0.7184375
            },
            {
              "distanceBp": 9,
              "samples": 4723,
              "probability": 0.7071776413296633
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 2,
        "endBp": 9,
        "calibrationScore": 0.009754475946048438,
        "coverageFraction": 0.5241791911550032
      }
    },
    {
      "asset": "eth",
      "windowCount": 315116,
      "alignedWindowShare": 0.513512484291499,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 4,
              "samples": 2786,
              "probability": 0.9641062455132807
            },
            {
              "distanceBp": 5,
              "samples": 3606,
              "probability": 0.9694952856350527
            },
            {
              "distanceBp": 6,
              "samples": 4352,
              "probability": 0.9719669117647058
            },
            {
              "distanceBp": 7,
              "samples": 5178,
              "probability": 0.9768250289687138
            },
            {
              "distanceBp": 8,
              "samples": 5516,
              "probability": 0.9800580130529369
            },
            {
              "distanceBp": 9,
              "samples": 5667,
              "probability": 0.9779424739721193
            },
            {
              "distanceBp": 10,
              "samples": 5806,
              "probability": 0.9836376162590423
            },
            {
              "distanceBp": 11,
              "samples": 5731,
              "probability": 0.9825510382132263
            },
            {
              "distanceBp": 12,
              "samples": 5506,
              "probability": 0.9865601162368326
            }
          ],
          "2": [
            {
              "distanceBp": 4,
              "samples": 2678,
              "probability": 0.9077669902912622
            },
            {
              "distanceBp": 5,
              "samples": 3537,
              "probability": 0.9165959852982754
            },
            {
              "distanceBp": 6,
              "samples": 4277,
              "probability": 0.9237783493102643
            },
            {
              "distanceBp": 7,
              "samples": 4818,
              "probability": 0.9261104192611042
            },
            {
              "distanceBp": 8,
              "samples": 5136,
              "probability": 0.929322429906542
            },
            {
              "distanceBp": 9,
              "samples": 5147,
              "probability": 0.939576452302312
            },
            {
              "distanceBp": 10,
              "samples": 5382,
              "probability": 0.9342251950947603
            },
            {
              "distanceBp": 11,
              "samples": 5164,
              "probability": 0.9490704879938032
            },
            {
              "distanceBp": 12,
              "samples": 4750,
              "probability": 0.9458947368421052
            }
          ],
          "3": [
            {
              "distanceBp": 4,
              "samples": 2495,
              "probability": 0.8629258517034069
            },
            {
              "distanceBp": 5,
              "samples": 3135,
              "probability": 0.8720893141945774
            },
            {
              "distanceBp": 6,
              "samples": 3640,
              "probability": 0.8703296703296703
            },
            {
              "distanceBp": 7,
              "samples": 3940,
              "probability": 0.8715736040609137
            },
            {
              "distanceBp": 8,
              "samples": 4239,
              "probability": 0.8780372729417315
            },
            {
              "distanceBp": 9,
              "samples": 4344,
              "probability": 0.8851289134438306
            },
            {
              "distanceBp": 10,
              "samples": 4183,
              "probability": 0.8919435811618456
            },
            {
              "distanceBp": 11,
              "samples": 4025,
              "probability": 0.8988819875776397
            },
            {
              "distanceBp": 12,
              "samples": 3720,
              "probability": 0.9018817204301075
            }
          ],
          "4": [
            {
              "distanceBp": 4,
              "samples": 1592,
              "probability": 0.8203517587939698
            },
            {
              "distanceBp": 5,
              "samples": 1952,
              "probability": 0.8048155737704918
            },
            {
              "distanceBp": 6,
              "samples": 2255,
              "probability": 0.8150776053215077
            },
            {
              "distanceBp": 7,
              "samples": 2254,
              "probability": 0.826530612244898
            },
            {
              "distanceBp": 8,
              "samples": 2341,
              "probability": 0.8175993165313968
            },
            {
              "distanceBp": 9,
              "samples": 2322,
              "probability": 0.842807924203273
            },
            {
              "distanceBp": 10,
              "samples": 2217,
              "probability": 0.8416779431664412
            },
            {
              "distanceBp": 11,
              "samples": 1986,
              "probability": 0.8444108761329305
            },
            {
              "distanceBp": 12,
              "samples": 1796,
              "probability": 0.8418708240534521
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 4,
              "samples": 17491,
              "probability": 0.8296838374020925
            },
            {
              "distanceBp": 5,
              "samples": 15190,
              "probability": 0.8504279131007242
            },
            {
              "distanceBp": 6,
              "samples": 12567,
              "probability": 0.8761040821198377
            },
            {
              "distanceBp": 7,
              "samples": 10352,
              "probability": 0.883500772797527
            },
            {
              "distanceBp": 8,
              "samples": 8711,
              "probability": 0.9011594535644587
            },
            {
              "distanceBp": 9,
              "samples": 6895,
              "probability": 0.908339376359681
            },
            {
              "distanceBp": 10,
              "samples": 5706,
              "probability": 0.9206098843322819
            },
            {
              "distanceBp": 11,
              "samples": 4608,
              "probability": 0.9327256944444444
            },
            {
              "distanceBp": 12,
              "samples": 3659,
              "probability": 0.9275758403935501
            }
          ],
          "2": [
            {
              "distanceBp": 4,
              "samples": 19077,
              "probability": 0.7470776327514809
            },
            {
              "distanceBp": 5,
              "samples": 16404,
              "probability": 0.7713972201901975
            },
            {
              "distanceBp": 6,
              "samples": 13809,
              "probability": 0.7915851980592368
            },
            {
              "distanceBp": 7,
              "samples": 11251,
              "probability": 0.8033063727668651
            },
            {
              "distanceBp": 8,
              "samples": 9176,
              "probability": 0.8273757628596339
            },
            {
              "distanceBp": 9,
              "samples": 7182,
              "probability": 0.8235867446393762
            },
            {
              "distanceBp": 10,
              "samples": 5789,
              "probability": 0.8365866298151667
            },
            {
              "distanceBp": 11,
              "samples": 4803,
              "probability": 0.8457214241099313
            },
            {
              "distanceBp": 12,
              "samples": 3961,
              "probability": 0.8487755617268367
            }
          ],
          "3": [
            {
              "distanceBp": 4,
              "samples": 21428,
              "probability": 0.6959585588949039
            },
            {
              "distanceBp": 5,
              "samples": 18010,
              "probability": 0.7153803442531926
            },
            {
              "distanceBp": 6,
              "samples": 14907,
              "probability": 0.7361642181525457
            },
            {
              "distanceBp": 7,
              "samples": 12123,
              "probability": 0.7418955704033655
            },
            {
              "distanceBp": 8,
              "samples": 9618,
              "probability": 0.7575379496776876
            },
            {
              "distanceBp": 9,
              "samples": 7770,
              "probability": 0.7599742599742599
            },
            {
              "distanceBp": 10,
              "samples": 6266,
              "probability": 0.7826364506862432
            },
            {
              "distanceBp": 11,
              "samples": 5053,
              "probability": 0.7771620819315258
            },
            {
              "distanceBp": 12,
              "samples": 3987,
              "probability": 0.7830448959117131
            }
          ],
          "4": [
            {
              "distanceBp": 4,
              "samples": 25057,
              "probability": 0.6501177315720158
            },
            {
              "distanceBp": 5,
              "samples": 19908,
              "probability": 0.665862969660438
            },
            {
              "distanceBp": 6,
              "samples": 15937,
              "probability": 0.6876451025914538
            },
            {
              "distanceBp": 7,
              "samples": 12597,
              "probability": 0.6919901563864412
            },
            {
              "distanceBp": 8,
              "samples": 9721,
              "probability": 0.7059973253780475
            },
            {
              "distanceBp": 9,
              "samples": 7634,
              "probability": 0.7144354204872937
            },
            {
              "distanceBp": 10,
              "samples": 6013,
              "probability": 0.719441210710128
            },
            {
              "distanceBp": 11,
              "samples": 4661,
              "probability": 0.7122934992490881
            },
            {
              "distanceBp": 12,
              "samples": 3672,
              "probability": 0.7322984749455338
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 4,
        "endBp": 12,
        "calibrationScore": 0.00967394079760359,
        "coverageFraction": 0.40551733329948336
      }
    },
    {
      "asset": "sol",
      "windowCount": 315116,
      "alignedWindowShare": 0.511821043679153,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 9,
              "samples": 2294,
              "probability": 0.9673060156931125
            },
            {
              "distanceBp": 10,
              "samples": 2886,
              "probability": 0.9691614691614692
            },
            {
              "distanceBp": 11,
              "samples": 3228,
              "probability": 0.9730483271375465
            },
            {
              "distanceBp": 12,
              "samples": 3533,
              "probability": 0.9762241720917068
            },
            {
              "distanceBp": 13,
              "samples": 3812,
              "probability": 0.9779643231899265
            },
            {
              "distanceBp": 14,
              "samples": 4076,
              "probability": 0.9796368989205103
            },
            {
              "distanceBp": 15,
              "samples": 4246,
              "probability": 0.9851625058878944
            },
            {
              "distanceBp": 16,
              "samples": 4162,
              "probability": 0.987986544930322
            },
            {
              "distanceBp": 17,
              "samples": 4166,
              "probability": 0.984637542006721
            },
            {
              "distanceBp": 18,
              "samples": 3974,
              "probability": 0.9869149471565174
            }
          ],
          "2": [
            {
              "distanceBp": 9,
              "samples": 2263,
              "probability": 0.9116217410517012
            },
            {
              "distanceBp": 10,
              "samples": 2728,
              "probability": 0.9197214076246334
            },
            {
              "distanceBp": 11,
              "samples": 3110,
              "probability": 0.9189710610932476
            },
            {
              "distanceBp": 12,
              "samples": 3489,
              "probability": 0.9317856119231872
            },
            {
              "distanceBp": 13,
              "samples": 3548,
              "probability": 0.9303833145434047
            },
            {
              "distanceBp": 14,
              "samples": 3867,
              "probability": 0.9405223687613137
            },
            {
              "distanceBp": 15,
              "samples": 3899,
              "probability": 0.9384457553218774
            },
            {
              "distanceBp": 16,
              "samples": 3642,
              "probability": 0.9398682042833608
            },
            {
              "distanceBp": 17,
              "samples": 3825,
              "probability": 0.9474509803921569
            },
            {
              "distanceBp": 18,
              "samples": 3608,
              "probability": 0.9495565410199557
            }
          ],
          "3": [
            {
              "distanceBp": 9,
              "samples": 2015,
              "probability": 0.8471464019851117
            },
            {
              "distanceBp": 10,
              "samples": 2522,
              "probability": 0.8774781919111816
            },
            {
              "distanceBp": 11,
              "samples": 2791,
              "probability": 0.8792547474023648
            },
            {
              "distanceBp": 12,
              "samples": 2906,
              "probability": 0.8857536132140399
            },
            {
              "distanceBp": 13,
              "samples": 3040,
              "probability": 0.8773026315789474
            },
            {
              "distanceBp": 14,
              "samples": 3177,
              "probability": 0.8772426817752597
            },
            {
              "distanceBp": 15,
              "samples": 3146,
              "probability": 0.8877940241576605
            },
            {
              "distanceBp": 16,
              "samples": 3137,
              "probability": 0.8912974179152056
            },
            {
              "distanceBp": 17,
              "samples": 3008,
              "probability": 0.8916223404255319
            },
            {
              "distanceBp": 18,
              "samples": 2866,
              "probability": 0.9047452896022331
            }
          ],
          "4": [
            {
              "distanceBp": 9,
              "samples": 1262,
              "probability": 0.8042789223454834
            },
            {
              "distanceBp": 10,
              "samples": 1462,
              "probability": 0.8255813953488372
            },
            {
              "distanceBp": 11,
              "samples": 1632,
              "probability": 0.8180147058823529
            },
            {
              "distanceBp": 12,
              "samples": 1706,
              "probability": 0.8311840562719812
            },
            {
              "distanceBp": 13,
              "samples": 1729,
              "probability": 0.8368999421631
            },
            {
              "distanceBp": 14,
              "samples": 1727,
              "probability": 0.8314997104806022
            },
            {
              "distanceBp": 15,
              "samples": 1622,
              "probability": 0.8310727496917386
            },
            {
              "distanceBp": 16,
              "samples": 1621,
              "probability": 0.8365206662553979
            },
            {
              "distanceBp": 17,
              "samples": 1440,
              "probability": 0.8298611111111112
            },
            {
              "distanceBp": 18,
              "samples": 1311,
              "probability": 0.84744469870328
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 9,
              "samples": 9466,
              "probability": 0.872807944221424
            },
            {
              "distanceBp": 10,
              "samples": 8215,
              "probability": 0.8842361533779671
            },
            {
              "distanceBp": 11,
              "samples": 7193,
              "probability": 0.8979563464479355
            },
            {
              "distanceBp": 12,
              "samples": 6221,
              "probability": 0.901141295611638
            },
            {
              "distanceBp": 13,
              "samples": 5364,
              "probability": 0.9049217002237137
            },
            {
              "distanceBp": 14,
              "samples": 4704,
              "probability": 0.9162414965986394
            },
            {
              "distanceBp": 15,
              "samples": 3900,
              "probability": 0.9225641025641026
            },
            {
              "distanceBp": 16,
              "samples": 3432,
              "probability": 0.9297785547785548
            },
            {
              "distanceBp": 17,
              "samples": 2992,
              "probability": 0.9224598930481284
            },
            {
              "distanceBp": 18,
              "samples": 2446,
              "probability": 0.9341782502044154
            }
          ],
          "2": [
            {
              "distanceBp": 9,
              "samples": 10027,
              "probability": 0.7933579335793358
            },
            {
              "distanceBp": 10,
              "samples": 9022,
              "probability": 0.8045887829749501
            },
            {
              "distanceBp": 11,
              "samples": 7658,
              "probability": 0.822016192217289
            },
            {
              "distanceBp": 12,
              "samples": 6434,
              "probability": 0.8319863226608641
            },
            {
              "distanceBp": 13,
              "samples": 5794,
              "probability": 0.8296513634794616
            },
            {
              "distanceBp": 14,
              "samples": 4840,
              "probability": 0.8274793388429752
            },
            {
              "distanceBp": 15,
              "samples": 4280,
              "probability": 0.835981308411215
            },
            {
              "distanceBp": 16,
              "samples": 3591,
              "probability": 0.8370927318295739
            },
            {
              "distanceBp": 17,
              "samples": 3032,
              "probability": 0.8420184696569921
            },
            {
              "distanceBp": 18,
              "samples": 2581,
              "probability": 0.8500581170089113
            }
          ],
          "3": [
            {
              "distanceBp": 9,
              "samples": 10939,
              "probability": 0.7347106682512112
            },
            {
              "distanceBp": 10,
              "samples": 9704,
              "probability": 0.7430956306677658
            },
            {
              "distanceBp": 11,
              "samples": 8253,
              "probability": 0.7508784684357204
            },
            {
              "distanceBp": 12,
              "samples": 7051,
              "probability": 0.7584739753226493
            },
            {
              "distanceBp": 13,
              "samples": 6021,
              "probability": 0.7732934728450424
            },
            {
              "distanceBp": 14,
              "samples": 5110,
              "probability": 0.7737769080234833
            },
            {
              "distanceBp": 15,
              "samples": 4354,
              "probability": 0.7742305925585669
            },
            {
              "distanceBp": 16,
              "samples": 3616,
              "probability": 0.7743362831858407
            },
            {
              "distanceBp": 17,
              "samples": 3222,
              "probability": 0.7849162011173184
            },
            {
              "distanceBp": 18,
              "samples": 2754,
              "probability": 0.7908496732026143
            }
          ],
          "4": [
            {
              "distanceBp": 9,
              "samples": 11571,
              "probability": 0.6844697951775992
            },
            {
              "distanceBp": 10,
              "samples": 10012,
              "probability": 0.6950659208949261
            },
            {
              "distanceBp": 11,
              "samples": 8388,
              "probability": 0.7021936099189318
            },
            {
              "distanceBp": 12,
              "samples": 7090,
              "probability": 0.704231311706629
            },
            {
              "distanceBp": 13,
              "samples": 5907,
              "probability": 0.718131030980193
            },
            {
              "distanceBp": 14,
              "samples": 4887,
              "probability": 0.72109678739513
            },
            {
              "distanceBp": 15,
              "samples": 4200,
              "probability": 0.7147619047619047
            },
            {
              "distanceBp": 16,
              "samples": 3534,
              "probability": 0.7266553480475382
            },
            {
              "distanceBp": 17,
              "samples": 2969,
              "probability": 0.7345907713034692
            },
            {
              "distanceBp": 18,
              "samples": 2613,
              "probability": 0.7405281285878301
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 9,
        "endBp": 18,
        "calibrationScore": 0.008961422993158606,
        "coverageFraction": 0.2636735360946445
      }
    },
    {
      "asset": "xrp",
      "windowCount": 315116,
      "alignedWindowShare": 0.5061469427131596,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 6,
              "samples": 2721,
              "probability": 0.9639838294744579
            },
            {
              "distanceBp": 7,
              "samples": 4014,
              "probability": 0.9691081215744893
            },
            {
              "distanceBp": 8,
              "samples": 3944,
              "probability": 0.9710953346855984
            },
            {
              "distanceBp": 9,
              "samples": 5383,
              "probability": 0.9739921976592978
            },
            {
              "distanceBp": 10,
              "samples": 4392,
              "probability": 0.9749544626593807
            },
            {
              "distanceBp": 11,
              "samples": 5780,
              "probability": 0.9820069204152249
            },
            {
              "distanceBp": 12,
              "samples": 4713,
              "probability": 0.9819647782728623
            },
            {
              "distanceBp": 13,
              "samples": 4984,
              "probability": 0.9863563402889246
            },
            {
              "distanceBp": 14,
              "samples": 4674,
              "probability": 0.9845956354300385
            },
            {
              "distanceBp": 15,
              "samples": 4587,
              "probability": 0.988009592326139
            }
          ],
          "2": [
            {
              "distanceBp": 6,
              "samples": 2548,
              "probability": 0.9010989010989011
            },
            {
              "distanceBp": 7,
              "samples": 3965,
              "probability": 0.9114754098360656
            },
            {
              "distanceBp": 8,
              "samples": 3867,
              "probability": 0.9190587018360487
            },
            {
              "distanceBp": 9,
              "samples": 4901,
              "probability": 0.9261375229544991
            },
            {
              "distanceBp": 10,
              "samples": 3914,
              "probability": 0.9394481349003577
            },
            {
              "distanceBp": 11,
              "samples": 5229,
              "probability": 0.9437751004016064
            },
            {
              "distanceBp": 12,
              "samples": 4202,
              "probability": 0.9469300333174678
            },
            {
              "distanceBp": 13,
              "samples": 4352,
              "probability": 0.9460018382352942
            },
            {
              "distanceBp": 14,
              "samples": 4069,
              "probability": 0.952076677316294
            },
            {
              "distanceBp": 15,
              "samples": 4072,
              "probability": 0.9584970530451866
            }
          ],
          "3": [
            {
              "distanceBp": 6,
              "samples": 2305,
              "probability": 0.8468546637744034
            },
            {
              "distanceBp": 7,
              "samples": 3333,
              "probability": 0.8577857785778578
            },
            {
              "distanceBp": 8,
              "samples": 3294,
              "probability": 0.8670309653916212
            },
            {
              "distanceBp": 9,
              "samples": 4122,
              "probability": 0.8791848617176128
            },
            {
              "distanceBp": 10,
              "samples": 3292,
              "probability": 0.8869987849331713
            },
            {
              "distanceBp": 11,
              "samples": 4196,
              "probability": 0.8951382268827455
            },
            {
              "distanceBp": 12,
              "samples": 3359,
              "probability": 0.9050312593033641
            },
            {
              "distanceBp": 13,
              "samples": 3476,
              "probability": 0.8990218642117376
            },
            {
              "distanceBp": 14,
              "samples": 3226,
              "probability": 0.9051456912585245
            },
            {
              "distanceBp": 15,
              "samples": 3100,
              "probability": 0.902258064516129
            }
          ],
          "4": [
            {
              "distanceBp": 6,
              "samples": 1528,
              "probability": 0.806282722513089
            },
            {
              "distanceBp": 7,
              "samples": 2135,
              "probability": 0.8112412177985948
            },
            {
              "distanceBp": 8,
              "samples": 1941,
              "probability": 0.8371973209685729
            },
            {
              "distanceBp": 9,
              "samples": 2283,
              "probability": 0.8462549277266754
            },
            {
              "distanceBp": 10,
              "samples": 1793,
              "probability": 0.8304517568321249
            },
            {
              "distanceBp": 11,
              "samples": 2186,
              "probability": 0.8316559926806953
            },
            {
              "distanceBp": 12,
              "samples": 1622,
              "probability": 0.844019728729963
            },
            {
              "distanceBp": 13,
              "samples": 1629,
              "probability": 0.850828729281768
            },
            {
              "distanceBp": 14,
              "samples": 1541,
              "probability": 0.8533419857235561
            },
            {
              "distanceBp": 15,
              "samples": 1313,
              "probability": 0.8461538461538461
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 6,
              "samples": 12739,
              "probability": 0.8531281890258262
            },
            {
              "distanceBp": 7,
              "samples": 10900,
              "probability": 0.8739449541284404
            },
            {
              "distanceBp": 8,
              "samples": 8904,
              "probability": 0.8835354896675651
            },
            {
              "distanceBp": 9,
              "samples": 7916,
              "probability": 0.8999494694290046
            },
            {
              "distanceBp": 10,
              "samples": 5901,
              "probability": 0.8995085578715472
            },
            {
              "distanceBp": 11,
              "samples": 5538,
              "probability": 0.9075478512098231
            },
            {
              "distanceBp": 12,
              "samples": 4263,
              "probability": 0.9066385174759559
            },
            {
              "distanceBp": 13,
              "samples": 3768,
              "probability": 0.9169320594479831
            },
            {
              "distanceBp": 14,
              "samples": 3037,
              "probability": 0.9170233783338821
            },
            {
              "distanceBp": 15,
              "samples": 2713,
              "probability": 0.9093254699594545
            }
          ],
          "2": [
            {
              "distanceBp": 6,
              "samples": 13557,
              "probability": 0.7757615991738586
            },
            {
              "distanceBp": 7,
              "samples": 11433,
              "probability": 0.7934050555409778
            },
            {
              "distanceBp": 8,
              "samples": 9633,
              "probability": 0.8043184885290149
            },
            {
              "distanceBp": 9,
              "samples": 8443,
              "probability": 0.8094279284614474
            },
            {
              "distanceBp": 10,
              "samples": 6196,
              "probability": 0.8152033570045191
            },
            {
              "distanceBp": 11,
              "samples": 5854,
              "probability": 0.8293474547318073
            },
            {
              "distanceBp": 12,
              "samples": 4589,
              "probability": 0.8208760078448464
            },
            {
              "distanceBp": 13,
              "samples": 3907,
              "probability": 0.8407985666751984
            },
            {
              "distanceBp": 14,
              "samples": 3297,
              "probability": 0.8425841674249318
            },
            {
              "distanceBp": 15,
              "samples": 2708,
              "probability": 0.8412112259970458
            }
          ],
          "3": [
            {
              "distanceBp": 6,
              "samples": 15037,
              "probability": 0.7221520250049877
            },
            {
              "distanceBp": 7,
              "samples": 12229,
              "probability": 0.738081609289394
            },
            {
              "distanceBp": 8,
              "samples": 10489,
              "probability": 0.7470683573267233
            },
            {
              "distanceBp": 9,
              "samples": 9052,
              "probability": 0.7539770216526734
            },
            {
              "distanceBp": 10,
              "samples": 6611,
              "probability": 0.7504159733777038
            },
            {
              "distanceBp": 11,
              "samples": 6136,
              "probability": 0.758800521512386
            },
            {
              "distanceBp": 12,
              "samples": 4681,
              "probability": 0.7675710318308053
            },
            {
              "distanceBp": 13,
              "samples": 4073,
              "probability": 0.7770684998772404
            },
            {
              "distanceBp": 14,
              "samples": 3425,
              "probability": 0.7705109489051095
            },
            {
              "distanceBp": 15,
              "samples": 2846,
              "probability": 0.7874209416725229
            }
          ],
          "4": [
            {
              "distanceBp": 6,
              "samples": 16391,
              "probability": 0.6756146665853212
            },
            {
              "distanceBp": 7,
              "samples": 13051,
              "probability": 0.682936173473297
            },
            {
              "distanceBp": 8,
              "samples": 10478,
              "probability": 0.6905898072151174
            },
            {
              "distanceBp": 9,
              "samples": 8987,
              "probability": 0.6928897296094358
            },
            {
              "distanceBp": 10,
              "samples": 6603,
              "probability": 0.6999848553687718
            },
            {
              "distanceBp": 11,
              "samples": 6133,
              "probability": 0.7066688406978641
            },
            {
              "distanceBp": 12,
              "samples": 4462,
              "probability": 0.712684894666069
            },
            {
              "distanceBp": 13,
              "samples": 3908,
              "probability": 0.7131525076765609
            },
            {
              "distanceBp": 14,
              "samples": 3191,
              "probability": 0.7405202130993419
            },
            {
              "distanceBp": 15,
              "samples": 2610,
              "probability": 0.725287356321839
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 6,
        "endBp": 15,
        "calibrationScore": 0.010933589130531869,
        "coverageFraction": 0.327107319209434
      }
    },
    {
      "asset": "doge",
      "windowCount": 315116,
      "alignedWindowShare": 0.511700453166453,
      "aligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 6,
              "samples": 2381,
              "probability": 0.9685006299874003
            },
            {
              "distanceBp": 7,
              "samples": 1895,
              "probability": 0.9646437994722955
            },
            {
              "distanceBp": 8,
              "samples": 3118,
              "probability": 0.977228992944195
            },
            {
              "distanceBp": 9,
              "samples": 3435,
              "probability": 0.97117903930131
            },
            {
              "distanceBp": 10,
              "samples": 3161,
              "probability": 0.9715279974691553
            },
            {
              "distanceBp": 11,
              "samples": 3964,
              "probability": 0.9772956609485368
            },
            {
              "distanceBp": 12,
              "samples": 4036,
              "probability": 0.9816650148662042
            },
            {
              "distanceBp": 13,
              "samples": 3826,
              "probability": 0.983533716675379
            },
            {
              "distanceBp": 14,
              "samples": 4126,
              "probability": 0.983034415899176
            },
            {
              "distanceBp": 15,
              "samples": 3840,
              "probability": 0.98515625
            },
            {
              "distanceBp": 16,
              "samples": 4069,
              "probability": 0.9869746866551978
            },
            {
              "distanceBp": 17,
              "samples": 3789,
              "probability": 0.9862760622855635
            }
          ],
          "2": [
            {
              "distanceBp": 6,
              "samples": 2224,
              "probability": 0.9118705035971223
            },
            {
              "distanceBp": 7,
              "samples": 1909,
              "probability": 0.9140911471974856
            },
            {
              "distanceBp": 8,
              "samples": 2946,
              "probability": 0.929735234215886
            },
            {
              "distanceBp": 9,
              "samples": 3249,
              "probability": 0.9190520160049246
            },
            {
              "distanceBp": 10,
              "samples": 2967,
              "probability": 0.9150657229524772
            },
            {
              "distanceBp": 11,
              "samples": 3714,
              "probability": 0.9372644049542272
            },
            {
              "distanceBp": 12,
              "samples": 3736,
              "probability": 0.9483404710920771
            },
            {
              "distanceBp": 13,
              "samples": 3509,
              "probability": 0.939013964092334
            },
            {
              "distanceBp": 14,
              "samples": 3695,
              "probability": 0.945872801082544
            },
            {
              "distanceBp": 15,
              "samples": 3509,
              "probability": 0.9467084639498433
            },
            {
              "distanceBp": 16,
              "samples": 3631,
              "probability": 0.944643348939686
            },
            {
              "distanceBp": 17,
              "samples": 3471,
              "probability": 0.9564966868337654
            }
          ],
          "3": [
            {
              "distanceBp": 6,
              "samples": 1918,
              "probability": 0.8660062565172054
            },
            {
              "distanceBp": 7,
              "samples": 1761,
              "probability": 0.8551959114139693
            },
            {
              "distanceBp": 8,
              "samples": 2439,
              "probability": 0.8761787617876179
            },
            {
              "distanceBp": 9,
              "samples": 2727,
              "probability": 0.8830216354968831
            },
            {
              "distanceBp": 10,
              "samples": 2575,
              "probability": 0.8671844660194175
            },
            {
              "distanceBp": 11,
              "samples": 3115,
              "probability": 0.8882825040128411
            },
            {
              "distanceBp": 12,
              "samples": 3023,
              "probability": 0.8991068475024809
            },
            {
              "distanceBp": 13,
              "samples": 2992,
              "probability": 0.9007352941176471
            },
            {
              "distanceBp": 14,
              "samples": 2984,
              "probability": 0.8800268096514745
            },
            {
              "distanceBp": 15,
              "samples": 2853,
              "probability": 0.8930949877322117
            },
            {
              "distanceBp": 16,
              "samples": 2812,
              "probability": 0.8986486486486487
            },
            {
              "distanceBp": 17,
              "samples": 2729,
              "probability": 0.8915353609380725
            }
          ],
          "4": [
            {
              "distanceBp": 6,
              "samples": 1268,
              "probability": 0.8201892744479495
            },
            {
              "distanceBp": 7,
              "samples": 1096,
              "probability": 0.8156934306569343
            },
            {
              "distanceBp": 8,
              "samples": 1504,
              "probability": 0.8344414893617021
            },
            {
              "distanceBp": 9,
              "samples": 1560,
              "probability": 0.8294871794871795
            },
            {
              "distanceBp": 10,
              "samples": 1486,
              "probability": 0.8135935397039031
            },
            {
              "distanceBp": 11,
              "samples": 1657,
              "probability": 0.8509354254677127
            },
            {
              "distanceBp": 12,
              "samples": 1597,
              "probability": 0.8303068252974327
            },
            {
              "distanceBp": 13,
              "samples": 1563,
              "probability": 0.8259756877799105
            },
            {
              "distanceBp": 14,
              "samples": 1480,
              "probability": 0.8486486486486486
            },
            {
              "distanceBp": 15,
              "samples": 1354,
              "probability": 0.8330871491875923
            },
            {
              "distanceBp": 16,
              "samples": 1438,
              "probability": 0.8317107093184979
            },
            {
              "distanceBp": 17,
              "samples": 1256,
              "probability": 0.839171974522293
            }
          ]
        }
      },
      "notAligned": {
        "byRemaining": {
          "1": [
            {
              "distanceBp": 6,
              "samples": 12607,
              "probability": 0.8375505671452368
            },
            {
              "distanceBp": 7,
              "samples": 10929,
              "probability": 0.853143013999451
            },
            {
              "distanceBp": 8,
              "samples": 9737,
              "probability": 0.868337270206429
            },
            {
              "distanceBp": 9,
              "samples": 8481,
              "probability": 0.8810281806390756
            },
            {
              "distanceBp": 10,
              "samples": 7111,
              "probability": 0.8877794965546336
            },
            {
              "distanceBp": 11,
              "samples": 6536,
              "probability": 0.9007037943696451
            },
            {
              "distanceBp": 12,
              "samples": 5490,
              "probability": 0.9061930783242259
            },
            {
              "distanceBp": 13,
              "samples": 4721,
              "probability": 0.9099766998517264
            },
            {
              "distanceBp": 14,
              "samples": 4095,
              "probability": 0.9147741147741147
            },
            {
              "distanceBp": 15,
              "samples": 3552,
              "probability": 0.9163851351351351
            },
            {
              "distanceBp": 16,
              "samples": 3125,
              "probability": 0.92544
            },
            {
              "distanceBp": 17,
              "samples": 2675,
              "probability": 0.9207476635514019
            }
          ],
          "2": [
            {
              "distanceBp": 6,
              "samples": 13874,
              "probability": 0.7628657921291625
            },
            {
              "distanceBp": 7,
              "samples": 11816,
              "probability": 0.7701421800947867
            },
            {
              "distanceBp": 8,
              "samples": 10684,
              "probability": 0.7941782104080869
            },
            {
              "distanceBp": 9,
              "samples": 9046,
              "probability": 0.797147910678753
            },
            {
              "distanceBp": 10,
              "samples": 7667,
              "probability": 0.8086604930220426
            },
            {
              "distanceBp": 11,
              "samples": 6823,
              "probability": 0.8129854902535542
            },
            {
              "distanceBp": 12,
              "samples": 5723,
              "probability": 0.8243928009785078
            },
            {
              "distanceBp": 13,
              "samples": 4976,
              "probability": 0.8193327974276527
            },
            {
              "distanceBp": 14,
              "samples": 4189,
              "probability": 0.8369539269515397
            },
            {
              "distanceBp": 15,
              "samples": 3751,
              "probability": 0.837110103972274
            },
            {
              "distanceBp": 16,
              "samples": 3239,
              "probability": 0.8413090460018524
            },
            {
              "distanceBp": 17,
              "samples": 2804,
              "probability": 0.8348787446504993
            }
          ],
          "3": [
            {
              "distanceBp": 6,
              "samples": 15115,
              "probability": 0.703274892490903
            },
            {
              "distanceBp": 7,
              "samples": 13066,
              "probability": 0.7212612888412674
            },
            {
              "distanceBp": 8,
              "samples": 11380,
              "probability": 0.7358523725834798
            },
            {
              "distanceBp": 9,
              "samples": 9804,
              "probability": 0.7451040391676866
            },
            {
              "distanceBp": 10,
              "samples": 8077,
              "probability": 0.7460690850563328
            },
            {
              "distanceBp": 11,
              "samples": 7238,
              "probability": 0.7594639403150042
            },
            {
              "distanceBp": 12,
              "samples": 6318,
              "probability": 0.767173156062045
            },
            {
              "distanceBp": 13,
              "samples": 5284,
              "probability": 0.7600302800908403
            },
            {
              "distanceBp": 14,
              "samples": 4549,
              "probability": 0.7685205539679051
            },
            {
              "distanceBp": 15,
              "samples": 3931,
              "probability": 0.7669804121088781
            },
            {
              "distanceBp": 16,
              "samples": 3358,
              "probability": 0.795116140559857
            },
            {
              "distanceBp": 17,
              "samples": 2915,
              "probability": 0.7938250428816467
            }
          ],
          "4": [
            {
              "distanceBp": 6,
              "samples": 17364,
              "probability": 0.6687975120939875
            },
            {
              "distanceBp": 7,
              "samples": 14626,
              "probability": 0.6778339942568029
            },
            {
              "distanceBp": 8,
              "samples": 12398,
              "probability": 0.6881755121793838
            },
            {
              "distanceBp": 9,
              "samples": 10436,
              "probability": 0.6947106170946723
            },
            {
              "distanceBp": 10,
              "samples": 8720,
              "probability": 0.705045871559633
            },
            {
              "distanceBp": 11,
              "samples": 7470,
              "probability": 0.7057563587684069
            },
            {
              "distanceBp": 12,
              "samples": 6271,
              "probability": 0.7030776590655398
            },
            {
              "distanceBp": 13,
              "samples": 5218,
              "probability": 0.7203909543886546
            },
            {
              "distanceBp": 14,
              "samples": 4539,
              "probability": 0.7116104868913857
            },
            {
              "distanceBp": 15,
              "samples": 3766,
              "probability": 0.7219861922464152
            },
            {
              "distanceBp": 16,
              "samples": 3231,
              "probability": 0.7226864747756113
            },
            {
              "distanceBp": 17,
              "samples": 2785,
              "probability": 0.7350089766606822
            }
          ]
        }
      },
      "sweetSpot": {
        "startBp": 6,
        "endBp": 17,
        "calibrationScore": 0.008964971702556626,
        "coverageFraction": 0.3618945086888638
      }
    }
  ]
};
