import { writeFile } from "node:fs/promises";

import type { ProbabilityTable } from "@alea/lib/trading/types";

/**
 * Writes the committed `probabilityTable.generated.ts` module that the
 * live trader imports at runtime. The module is intentionally a single
 * `export const` so it type-checks like any other code in the repo —
 * no JSON imports, no async load, no parse step on the hot path.
 *
 * The file header is stamped with a "do not edit" warning and the
 * generation timestamp; everything else is `JSON.stringify`-pretty-
 * printed for diff readability. The file is committed to version
 * control on purpose: refreshing the table is a deliberate act, and
 * the diff is the audit trail.
 */
export async function writeProbabilityTableModule({
  table,
  path,
}: {
  readonly table: ProbabilityTable;
  readonly path: string;
}): Promise<void> {
  const banner = [
    "/**",
    " * AUTO-GENERATED by `bun alea trading:gen-probability-table`.",
    " *",
    " * Do not edit by hand. Re-run the command to refresh; the live trader",
    " * loads this exact value at boot, so a stale table here means a stale",
    " * model in production.",
    " */",
    "",
    'import type { ProbabilityTable } from "@alea/lib/trading/types";',
    "",
    "export const probabilityTable: ProbabilityTable = ",
  ].join("\n");

  const body = JSON.stringify(table, null, 2);
  const contents = `${banner}${body};\n`;
  await writeFile(path, contents, "utf8");
}
