import { assetSchema } from "@alea/types/assets";
import { candleSeriesSchema } from "@alea/types/candleSeries";
import { z } from "zod";

/**
 * Inside a 5-minute window, which side of the open price ("line") is the
 * spot price currently sitting on. The training pipeline calls these
 * "up"/"down" as well, so the codename matches end to end.
 */
export const leadingSideSchema = z.enum(["up", "down"]);
export type LeadingSide = z.infer<typeof leadingSideSchema>;

/**
 * Minutes left in the 5m window at the moment of the snapshot. The model
 * only knows about the four discrete in-window minute boundaries, so live
 * decisioning floors current `(windowEnd - now)` to land on one of these.
 */
export const remainingMinutesSchema = z.union([
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
]);
export type RemainingMinutes = z.infer<typeof remainingMinutesSchema>;

/**
 * One `(distanceBp, samples, probability)` row of the surface. `probability`
 * is the empirical share of historical snapshots in this bucket whose
 * leading side matched the eventual settlement side — i.e. the probability
 * that "the side currently in the lead at this distance with this much time
 * remaining holds to close."
 *
 * Buckets with fewer than `MIN_BUCKET_SAMPLES` observations are dropped at
 * generation time; the live lookup never sees them.
 */
export const probabilityBucketSchema = z.object({
  distanceBp: z.int().nonnegative(),
  samples: z.int().positive(),
  probability: z.number().min(0).max(1),
});
export type ProbabilityBucket = z.infer<typeof probabilityBucketSchema>;

/**
 * For one `(asset, alignment)` pair, the four probability curves keyed by
 * remaining minutes. Each curve is a list of buckets sorted ascending by
 * `distanceBp` with no gaps suppressed (zero-sample buckets are simply
 * absent — this keeps the on-disk representation compact).
 */
export const probabilitySurfaceSchema = z.object({
  byRemaining: z.object({
    1: z.array(probabilityBucketSchema).readonly(),
    2: z.array(probabilityBucketSchema).readonly(),
    3: z.array(probabilityBucketSchema).readonly(),
    4: z.array(probabilityBucketSchema).readonly(),
  }),
});
export type ProbabilitySurface = z.infer<typeof probabilitySurfaceSchema>;

/**
 * The contiguous bp range where the active filter does most of its
 * work. Computed at training-data analysis time and applied as a
 * bucket-level filter when generating the probability table — buckets
 * outside this range are dropped, so the live lookup naturally returns
 * `null` there and the runner skips the trade. See
 * doc/research/2026-05-04-sweet-spot.md for the rationale.
 */
export const sweetSpotSchema = z.object({
  startBp: z.int().nonnegative(),
  endBp: z.int().nonnegative(),
  calibrationScore: z.number(),
  coverageFraction: z.number().min(0).max(1),
});
export type SweetSpot = z.infer<typeof sweetSpotSchema>;

/**
 * Per-asset payload: two surfaces produced by the active filter
 * (`distance_from_line_atr` as of the May 2026 promotion: `aligned` =
 * "decisively away" iff `|distance| ≥ 0.5 × ATR-14`, `notAligned` =
 * "near the line"), plus the window count each was derived from and
 * the per-asset sweet-spot range that bounds the persisted buckets.
 *
 * `windowCount` is the number of *5m windows*, not snapshots; each
 * window contributes up to four snapshots (one per remaining-minute
 * slot) and is split between the two surfaces by the filter. Names
 * `aligned` / `notAligned` are kept for back-compat with the existing
 * runtime code; they don't refer to EMA-50 alignment anymore.
 */
export const assetProbabilitiesSchema = z.object({
  asset: assetSchema,
  windowCount: z.int().nonnegative(),
  alignedWindowShare: z.number().min(0).max(1),
  aligned: probabilitySurfaceSchema,
  notAligned: probabilitySurfaceSchema,
  sweetSpot: sweetSpotSchema,
});
export type AssetProbabilities = z.infer<typeof assetProbabilitiesSchema>;

/**
 * The committed, version-controlled probability table the live runner
 * trades against. Generated by `bun alea trading:gen-probability-table`
 * from the local Postgres training data and serialized to disk under
 * `src/lib/trading/probabilityTable/`.
 *
 * Every consumer at runtime goes through `lookupProbability` rather than
 * indexing this structure directly, so the shape can evolve without
 * thrashing the call sites.
 */
export const probabilityTableSchema = z.object({
  command: z.literal("trading:gen-probability-table"),
  schemaVersion: z.literal(1),
  generatedAtMs: z.int(),
  series: candleSeriesSchema,
  /**
   * Sample-count floor used when materializing this table. Buckets below
   * this threshold were dropped. Stored on the table itself so the live
   * lookup never has to know which floor was applied.
   */
  minBucketSamples: z.int().positive(),
  /**
   * Earliest and latest 5m window-start timestamps observed across all
   * assets. Useful for sanity-checking that the table is fresh enough.
   */
  trainingRangeMs: z.object({
    firstWindowMs: z.int(),
    lastWindowMs: z.int(),
  }),
  assets: z.array(assetProbabilitiesSchema).readonly(),
});
export type ProbabilityTable = z.infer<typeof probabilityTableSchema>;
